FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    libtool \
    autotools-dev \
    autoconf \
    pkg-config \
    automake \
    python3 \
    bsdmainutils \
    zip \
    unzip \
    curl \
    ca-certificates \
    libqt5svg5-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /kristatech
